  main.cpp
f:\1.work\1.study\language\c++\test\c++\day09\02异常基本处理\main.cpp(67): warning C4297: “testFunc1”: 假定函数不引发异常，但确实发生了
  f:\1.work\1.study\language\c++\test\c++\day09\02异常基本处理\main.cpp(67): note: 在函数上指定了 __declspec(nothrow)、throw()、noexcept(true)或 noexcept
f:\1.work\1.study\language\c++\test\c++\day09\02异常基本处理\main.cpp(69): warning C4290: 忽略 C++ 异常规范，但指示函数不是 __declspec(nothrow)
  02异常基本处理.vcxproj -> F:\1.Work\1.Study\Language\C++\Test\C++\day09\Debug\02异常基本处理.exe
